project:
  type: website

lightbox: auto

author: Lino Galiana

validate-yaml: false
jupyter: python3

wrap: preserve
#cache: true


#bibliography: references.bib


citation:
  title: "Python pour la data science"
  author: Lino Galiana
  type: book
  doi: "10.5281/zenodo.8229676"
  url: https://pythonds.linogaliana.fr/
  issued: 2023

google-scholar: true

commentable: true
